const seasonMock = {
  airDate: '2024-07-17',
  episodes: [
    {
      airDate: '2024-07-18',
      crew: [Array],
      episodeNumber: 1,
      episodeType: 'standard',
      guestStars: [Array],
      id: 5319101,
      name: 'Peacetime in the Valley',
      overview:
        'The Miyagi-Do students struggle to put aside past rivalries while training for the Sekai Taikai. Johnny and Chozen clash over rebranding the dojo.',
      productionCode: '',
      runtime: 36,
      seasonNumber: 6,
      showId: 77169,
      stillPath: '/hYlkiTMMr8zF8ceSdudnP7AGHHl.jpg',
      voteAverage: 8.1,
      voteCount: 70,
    },
    {
      airDate: '2024-07-18',
      crew: [Array],
      episodeNumber: 2,
      episodeType: 'standard',
      guestStars: [Array],
      id: 5319102,
      name: 'The Prize',
      overview:
        'Kreese faces a dangerous test to prove his worthiness. Daniel offers Johnny a helping hand while the teens contemplate life beyond high school.',
      productionCode: '',
      runtime: 39,
      seasonNumber: 6,
      showId: 77169,
      stillPath: '/fI7BEdDnjK1X25pbeG7A7mKbAcC.jpg',
      voteAverage: 7.7,
      voteCount: 24,
    },
    {
      airDate: '2024-07-18',
      crew: [Array],
      episodeNumber: 3,
      episodeType: 'standard',
      guestStars: [Array],
      id: 5319103,
      name: 'Sleeper',
      overview:
        "A shocking discovery turns Daniel's world upside down. Johnny schemes a way to give Sam and Tory their edge back. The tournament reveals its location.",
      productionCode: '',
      runtime: 37,
      seasonNumber: 6,
      showId: 77169,
      stillPath: '/36ypCuCP0JIZZkJ3c6yskhMCks6.jpg',
      voteAverage: 7.9,
      voteCount: 20,
    },
    {
      airDate: '2024-07-18',
      crew: [Array],
      episodeNumber: 4,
      episodeType: 'standard',
      guestStars: [Array],
      id: 5319104,
      name: 'Underdogs',
      overview:
        'Daniel and Johnny invite a new sensei to evaluate their students. Friends become foes as the competition heats up for a spot in the Sekai Taikai.',
      productionCode: '',
      runtime: 37,
      seasonNumber: 6,
      showId: 77169,
      stillPath: '/casOxbUTCtBuXAuwoCPoJeSIjqz.jpg',
      voteAverage: 8.722,
      voteCount: 18,
    },
    {
      airDate: '2024-07-18',
      crew: [Array],
      episodeNumber: 5,
      episodeType: 'mid_season',
      guestStars: [Array],
      id: 5319105,
      name: 'Best of the Best',
      overview:
        "Miyagi-Do's top students square off to be team captains, but a devastating tragedy changes everything. Kreese reveals his final surprise.",
      productionCode: '',
      runtime: 45,
      seasonNumber: 6,
      showId: 77169,
      stillPath: '/dzf8E8jr9ywTn0nPYuq2eZ0eT3L.jpg',
      voteAverage: 8.7,
      voteCount: 21,
    },
    {
      airDate: '2024-11-15',
      crew: [Array],
      episodeNumber: 6,
      episodeType: 'standard',
      guestStars: [Array],
      id: 5319106,
      name: 'Benvinguts a Barcelona',
      overview:
        'With the Sekai Taikai underway, a betrayal threatens to throw team Miyagi-Do off their game. A dramatic first event unleashes the element of surprise.',
      productionCode: '',
      runtime: 38,
      seasonNumber: 6,
      showId: 77169,
      stillPath: '/kfFoyd5x4ZkMgCP1daw1ugb8qwe.jpg',
      voteAverage: 8.4,
      voteCount: 12,
    },
    {
      airDate: '2024-11-15',
      crew: [Array],
      episodeNumber: 7,
      episodeType: 'standard',
      guestStars: [Array],
      id: 5319107,
      name: 'Dog in the Fight',
      overview:
        "The search for clues about Mr. Miyagi's past leads Daniel into danger. Miguel raises doubts about Robby's focus. Sam observes ugly behavior off the mat.",
      productionCode: '',
      runtime: 39,
      seasonNumber: 6,
      showId: 77169,
      stillPath: '/Qv4vp5zzBdjPj2fUn0OHEijBWe.jpg',
      voteAverage: 8,
      voteCount: 11,
    },
    {
      airDate: '2024-11-15',
      crew: [Array],
      episodeNumber: 8,
      episodeType: 'standard',
      guestStars: [Array],
      id: 5319108,
      name: 'Snakes on a Plane',
      overview:
        'A personal crisis shakes Miguel and Johnny to the core. Chozen and a rival sensei team up to find their students — but discover something else instead.',
      productionCode: '',
      runtime: 38,
      seasonNumber: 6,
      showId: 77169,
      stillPath: '/hORd9qKMMWYogVldmc1rmn99XCu.jpg',
      voteAverage: 8.3,
      voteCount: 15,
    },
    {
      airDate: '2024-11-15',
      crew: [Array],
      episodeNumber: 9,
      episodeType: 'standard',
      guestStars: [Array],
      id: 5319109,
      name: 'Blood In Blood Out',
      overview:
        "Who will move to the next round in the tournament's tag team elimination match: Miyagi-Do or Cobra Kai? A shocking revelation shatters Daniel's world.",
      productionCode: '',
      runtime: 40,
      seasonNumber: 6,
      showId: 77169,
      stillPath: '/t4fTFhIScrSRfxddYyWgfaMCoQe.jpg',
      voteAverage: 8.8,
      voteCount: 13,
    },
    {
      airDate: '2024-11-15',
      crew: [Array],
      episodeNumber: 10,
      episodeType: 'mid_season',
      guestStars: [Array],
      id: 5319110,
      name: 'Eunjangdo',
      overview:
        'Daniel and Johnny use historic Barcelona as a training ground for their captains. But a cheap shot in the semifinals sparks a brawl to end all brawls.',
      productionCode: '',
      runtime: 47,
      seasonNumber: 6,
      showId: 77169,
      stillPath: '/w1U9Icf1YnnyxutZ633FBo6bjS3.jpg',
      voteAverage: 9,
      voteCount: 12,
    },
    {
      airDate: '2025-02-13',
      crew: [Array],
      episodeNumber: 11,
      episodeType: 'standard',
      guestStars: [Array],
      id: 5505561,
      name: 'Into the Fire',
      overview:
        'While their students plan for life after karate, Daniel and Johnny clash over reviving the Sekai Taikai. Kreese reconsiders his guiding principles.',
      productionCode: '',
      runtime: 40,
      seasonNumber: 6,
      showId: 77169,
      stillPath: '/lvPYAcVp35MEYAdg0N4IaoK1GKo.jpg',
      voteAverage: 8.9,
      voteCount: 11,
    },
    {
      airDate: '2025-02-13',
      crew: [Array],
      episodeNumber: 12,
      episodeType: 'standard',
      guestStars: [Array],
      id: 5505562,
      name: 'Rattled',
      overview:
        'Sam and Robby turn to their friends for support as they train for the challenges ahead. Johnny and Carmen welcome a new addition to the team.',
      productionCode: '',
      runtime: 40,
      seasonNumber: 6,
      showId: 77169,
      stillPath: '/85cl8xRS8JbEBKF5djmuwCpvw2d.jpg',
      voteAverage: 9,
      voteCount: 4,
    },
    {
      airDate: '2025-02-13',
      crew: [Array],
      episodeNumber: 13,
      episodeType: 'standard',
      guestStars: [Array],
      id: 5505563,
      name: 'Skeletons',
      overview:
        "As the moment of truth arrives, Daniel and Johnny confront their pasts. Then it's fight time as Robby battles Axel in the world karate championship.",
      productionCode: '',
      runtime: 39,
      seasonNumber: 6,
      showId: 77169,
      stillPath: '/vtUyWT7A4jFEwRkCOftWe4dnDah.jpg',
      voteAverage: 9.4,
      voteCount: 5,
    },
    {
      airDate: '2025-02-13',
      crew: [Array],
      episodeNumber: 14,
      episodeType: 'standard',
      guestStars: [Array],
      id: 5505564,
      name: 'Strike Last',
      overview:
        "The action heats up as the Valley's top fighters pit their courage against their rivals' speed and strength. But one last surprise changes everything.",
      productionCode: '',
      runtime: 47,
      seasonNumber: 6,
      showId: 77169,
      stillPath: '/h6mL6phWGSmotkj0nr4AqUNFhHb.jpg',
      voteAverage: 9.2,
      voteCount: 4,
    },
    {
      airDate: '2025-02-13',
      crew: [Array],
      episodeNumber: 15,
      episodeType: 'finale',
      guestStars: [Array],
      id: 5505565,
      name: 'Ex-Degenerate',
      overview:
        'Fierce rivalries. Fresh opportunities. Daniel and Johnny find themselves back where it all began — and the stakes have never been higher.',
      productionCode: '',
      runtime: 49,
      seasonNumber: 6,
      showId: 77169,
      stillPath: '/tfB0zgSSPV5jpa0PM2iycDjQ70p.jpg',
      voteAverage: 9.8,
      voteCount: 4,
    },
  ],
  id: 325233,
  name: 'Season 6',
  overview:
    'With the global tournament approaching, Daniel and Johnny work to rebuild their team. But old enemies and new threats stand in the way of victory.',
  posterPath: '/dC88tPr0RwuKe0O16hh8AevlKcO.jpg',
  seasonNumber: 6,
};
