const shows = [
  {
    adult: false,
    backdrop_path: '/mQJVtl7SYjNLwjsUZZsITmAxtdU.jpg',
    created_by: [
      {
        credit_id: '5ab36c76c3a368615b004c6e',
        gender: 2,
        id: 347335,
        name: 'Josh Heald',
        original_name: 'Josh Heald',
        profile_path: '/gAGqe7l5VMTdVZuah2YczbXOJUl.jpg',
      },
      {
        credit_id: '5ab47d649251417b020149ed',
        gender: 2,
        id: 68844,
        name: 'Hayden Schlossberg',
        original_name: 'Hayden Schlossberg',
        profile_path: '/kLkKtht08e9Z451RpD5l5ebpwZu.jpg',
      },
      {
        credit_id: '64511fa5e942ee0e37e700e5',
        gender: 2,
        id: 68843,
        name: 'Jon Hurwitz',
        original_name: 'Jon Hurwitz',
        profile_path: '/fl3yAMOLbQFF86m8amwH2Ufntjs.jpg',
      },
    ],
    episode_run_time: [],
    first_air_date: '2018-05-02',
    genres: [
      { id: 10759, name: 'Action & Adventure' },
      { id: 18, name: 'Drama' },
      { id: 35, name: 'Comedy' },
    ],
    homepage: 'https://www.netflix.com/title/81002370',
    id: 77169,
    in_production: false,
    languages: ['en'],
    last_air_date: '2025-02-13',
    last_episode_to_air: {
      air_date: '2025-02-13',
      episode_number: 15,
      episode_type: 'finale',
      id: 5505565,
      name: 'Ex-Degenerate',
      overview:
        'Fierce rivalries. Fresh opportunities. Daniel and Johnny find themselves back where it all began — and the stakes have never been higher.',
      production_code: '',
      runtime: 49,
      season_number: 6,
      show_id: 77169,
      still_path: '/tfB0zgSSPV5jpa0PM2iycDjQ70p.jpg',
      vote_average: 9.8,
      vote_count: 4,
    },
    name: 'Cobra Kai',
    networks: [
      {
        id: 213,
        logo_path: '/wwemzKWzjKYJFfCeiB57q3r4Bcm.png',
        name: 'Netflix',
        origin_country: '',
      },
      {
        id: 1436,
        logo_path: '/291gKkFoCfbpKXJD2jMn3QeZlJ4.png',
        name: 'YouTube Premium',
        origin_country: 'US',
      },
    ],
    next_episode_to_air: null,
    number_of_episodes: 65,
    number_of_seasons: 6,
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Cobra Kai',
    overview:
      'This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.',
    popularity: 2389.765,
    poster_path: '/6GDW4EsgsXlYrL1ASb5eCHQK4er.jpg',
    production_companies: [
      {
        id: 101024,
        logo_path: null,
        name: 'Hurwitz & Schlossberg Productions',
        origin_country: 'US',
      },
      {
        id: 11073,
        logo_path: '/aCbASRcI1MI7DXjPbSW9Fcv9uGR.png',
        name: 'Sony Pictures Television',
        origin_country: 'US',
      },
      {
        id: 907,
        logo_path: '/ca5SWI5uvU985f8Kbb4xc8AmVWH.png',
        name: 'Overbrook Entertainment',
        origin_country: 'US',
      },
    ],
    production_countries: [
      { iso_3166_1: 'US', name: 'United States of America' },
    ],
    seasons: [
      {
        air_date: '2018-05-02',
        episode_count: 10,
        id: 99459,
        name: 'Season 1',
        overview:
          'Decades after the tournament that changed their lives, the rivalry between Johnny and Daniel reignites.',
        poster_path: '/lLrKXnM3WPEtrPCd1aTHT6x3hn.jpg',
        season_number: 1,
        vote_average: 8.2,
      },
      {
        air_date: '2019-04-24',
        episode_count: 10,
        id: 120052,
        name: 'Season 2',
        overview:
          'Johnny continues building a new life, but a face from his past could disrupt his future. Meanwhile, Daniel opens a Miyagi-Do studio to rival Cobra Kai.',
        poster_path: '/77kyNXN6yCRjDt9eBMj96vLMx8W.jpg',
        season_number: 2,
        vote_average: 8.1,
      },
      {
        air_date: '2021-01-01',
        episode_count: 10,
        id: 160283,
        name: 'Season 3',
        overview:
          'With a new sensei at the helm of the Cobra Kai dojo, a three-way feud takes center stage. Old grudges — like Cobra Kai — never die.',
        poster_path: '/f9ccj6MfeAsOk1qAqpifJwzxdfn.jpg',
        season_number: 3,
        vote_average: 8.2,
      },
      {
        air_date: '2021-12-31',
        episode_count: 10,
        id: 197131,
        name: 'Season 4',
        overview:
          'Faced with a common enemy, Daniel and Johnny decide to start working together while Kreese looks to the past for a new ally of his own.',
        poster_path: '/hETMqMZYTBtVrA4A8AcLw5w76Xa.jpg',
        season_number: 4,
        vote_average: 8.5,
      },
      {
        air_date: '2022-09-09',
        episode_count: 10,
        id: 292695,
        name: 'Season 5',
        overview:
          'As Terry leads Cobra Kai into a new regime, Daniel, Johnny and an old ally join forces in a battle that goes way beyond the mat.',
        poster_path: '/u2o6NDi5aNQ3SfyN1kZSXBaKoHK.jpg',
        season_number: 5,
        vote_average: 8.2,
      },
      {
        air_date: '2024-07-17',
        episode_count: 15,
        id: 325233,
        name: 'Season 6',
        overview:
          'With the global tournament approaching, Daniel and Johnny work to rebuild their team. But old enemies and new threats stand in the way of victory.',
        poster_path: '/dC88tPr0RwuKe0O16hh8AevlKcO.jpg',
        season_number: 6,
        vote_average: 8.7,
      },
    ],
    spoken_languages: [
      { english_name: 'English', iso_639_1: 'en', name: 'English' },
    ],
    status: 'Ended',
    tagline: 'Back in the Valley. One final fight.',
    type: 'Scripted',
    vote_average: 8.211,
    vote_count: 6451,
  },
  {
    adult: false,
    backdrop_path: '/mQJVtl7SYjNLwjsUZZsITmAxtdU.jpg',
    created_by: [
      {
        credit_id: '5ab36c76c3a368615b004c6e',
        gender: 2,
        id: 347335,
        name: 'Josh Heald',
        original_name: 'Josh Heald',
        profile_path: '/gAGqe7l5VMTdVZuah2YczbXOJUl.jpg',
      },
      {
        credit_id: '5ab47d649251417b020149ed',
        gender: 2,
        id: 68844,
        name: 'Hayden Schlossberg',
        original_name: 'Hayden Schlossberg',
        profile_path: '/kLkKtht08e9Z451RpD5l5ebpwZu.jpg',
      },
      {
        credit_id: '64511fa5e942ee0e37e700e5',
        gender: 2,
        id: 68843,
        name: 'Jon Hurwitz',
        original_name: 'Jon Hurwitz',
        profile_path: '/fl3yAMOLbQFF86m8amwH2Ufntjs.jpg',
      },
    ],
    episode_run_time: [],
    first_air_date: '2018-05-02',
    genres: [
      { id: 10759, name: 'Action & Adventure' },
      { id: 18, name: 'Drama' },
      { id: 35, name: 'Comedy' },
    ],
    homepage: 'https://www.netflix.com/title/81002370',
    id: 77169,
    in_production: false,
    languages: ['en'],
    last_air_date: '2025-02-13',
    last_episode_to_air: {
      air_date: '2025-02-13',
      episode_number: 15,
      episode_type: 'finale',
      id: 5505565,
      name: 'Ex-Degenerate',
      overview:
        'Fierce rivalries. Fresh opportunities. Daniel and Johnny find themselves back where it all began — and the stakes have never been higher.',
      production_code: '',
      runtime: 49,
      season_number: 6,
      show_id: 77169,
      still_path: '/tfB0zgSSPV5jpa0PM2iycDjQ70p.jpg',
      vote_average: 9.8,
      vote_count: 4,
    },
    name: 'Cobra Kai',
    networks: [
      {
        id: 213,
        logo_path: '/wwemzKWzjKYJFfCeiB57q3r4Bcm.png',
        name: 'Netflix',
        origin_country: '',
      },
      {
        id: 1436,
        logo_path: '/291gKkFoCfbpKXJD2jMn3QeZlJ4.png',
        name: 'YouTube Premium',
        origin_country: 'US',
      },
    ],
    next_episode_to_air: null,
    number_of_episodes: 65,
    number_of_seasons: 6,
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Cobra Kai',
    overview:
      'This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.',
    popularity: 2389.765,
    poster_path: '/6GDW4EsgsXlYrL1ASb5eCHQK4er.jpg',
    production_companies: [
      {
        id: 101024,
        logo_path: null,
        name: 'Hurwitz & Schlossberg Productions',
        origin_country: 'US',
      },
      {
        id: 11073,
        logo_path: '/aCbASRcI1MI7DXjPbSW9Fcv9uGR.png',
        name: 'Sony Pictures Television',
        origin_country: 'US',
      },
      {
        id: 907,
        logo_path: '/ca5SWI5uvU985f8Kbb4xc8AmVWH.png',
        name: 'Overbrook Entertainment',
        origin_country: 'US',
      },
    ],
    production_countries: [
      { iso_3166_1: 'US', name: 'United States of America' },
    ],
    seasons: [
      {
        air_date: '2018-05-02',
        episode_count: 10,
        id: 99459,
        name: 'Season 1',
        overview:
          'Decades after the tournament that changed their lives, the rivalry between Johnny and Daniel reignites.',
        poster_path: '/lLrKXnM3WPEtrPCd1aTHT6x3hn.jpg',
        season_number: 1,
        vote_average: 8.2,
      },
      {
        air_date: '2019-04-24',
        episode_count: 10,
        id: 120052,
        name: 'Season 2',
        overview:
          'Johnny continues building a new life, but a face from his past could disrupt his future. Meanwhile, Daniel opens a Miyagi-Do studio to rival Cobra Kai.',
        poster_path: '/77kyNXN6yCRjDt9eBMj96vLMx8W.jpg',
        season_number: 2,
        vote_average: 8.1,
      },
      {
        air_date: '2021-01-01',
        episode_count: 10,
        id: 160283,
        name: 'Season 3',
        overview:
          'With a new sensei at the helm of the Cobra Kai dojo, a three-way feud takes center stage. Old grudges — like Cobra Kai — never die.',
        poster_path: '/f9ccj6MfeAsOk1qAqpifJwzxdfn.jpg',
        season_number: 3,
        vote_average: 8.2,
      },
      {
        air_date: '2021-12-31',
        episode_count: 10,
        id: 197131,
        name: 'Season 4',
        overview:
          'Faced with a common enemy, Daniel and Johnny decide to start working together while Kreese looks to the past for a new ally of his own.',
        poster_path: '/hETMqMZYTBtVrA4A8AcLw5w76Xa.jpg',
        season_number: 4,
        vote_average: 8.5,
      },
      {
        air_date: '2022-09-09',
        episode_count: 10,
        id: 292695,
        name: 'Season 5',
        overview:
          'As Terry leads Cobra Kai into a new regime, Daniel, Johnny and an old ally join forces in a battle that goes way beyond the mat.',
        poster_path: '/u2o6NDi5aNQ3SfyN1kZSXBaKoHK.jpg',
        season_number: 5,
        vote_average: 8.2,
      },
      {
        air_date: '2024-07-17',
        episode_count: 15,
        id: 325233,
        name: 'Season 6',
        overview:
          'With the global tournament approaching, Daniel and Johnny work to rebuild their team. But old enemies and new threats stand in the way of victory.',
        poster_path: '/dC88tPr0RwuKe0O16hh8AevlKcO.jpg',
        season_number: 6,
        vote_average: 8.7,
      },
    ],
    spoken_languages: [
      { english_name: 'English', iso_639_1: 'en', name: 'English' },
    ],
    status: 'Ended',
    tagline: 'Back in the Valley. One final fight.',
    type: 'Scripted',
    vote_average: 8.211,
    vote_count: 6451,
  },
  {
    adult: false,
    backdrop_path: '/odVlTMqPPiMksmxpN9cCbPCjUPP.jpg',
    created_by: [],
    episode_run_time: [24],
    first_air_date: '2024-01-07',
    genres: [
      { id: 10759, name: 'Action & Adventure' },
      { id: 10765, name: 'Sci-Fi & Fantasy' },
      { id: 16, name: 'Animation' },
    ],
    homepage: 'https://sololeveling-anime.net',
    id: 127532,
    in_production: true,
    languages: ['ja'],
    last_air_date: '2025-02-09',
    last_episode_to_air: {
      air_date: '2025-02-16',
      episode_number: 19,
      episode_type: 'standard',
      id: 5891814,
      name: 'The 10th S-Rank Hunter',
      overview:
        "Jinwoo officially becomes an S-Rank hunter, allowing him to finalize his preparations for the Demon's Castle.",
      production_code: '',
      runtime: 24,
      season_number: 1,
      show_id: 127532,
      still_path: '/zmRqLXqOMR2zVJ7bn9wwBsakOKh.jpg',
      vote_average: 9,
      vote_count: 2,
    },
    name: 'Solo Leveling',
    networks: [
      {
        id: 343,
        logo_path: '/9rNqtDYAnD6yTOutvHI3synSEs2.png',
        name: 'Gunma TV',
        origin_country: 'JP',
      },
      {
        id: 614,
        logo_path: '/hSdroyVthq3CynxTIIY7lnS8w1.png',
        name: 'Tokyo MX',
        origin_country: 'JP',
      },
      {
        id: 861,
        logo_path: '/JQ5bx6n7Qmdmyqz6sqjo5Fz2iR.png',
        name: 'BS11',
        origin_country: 'JP',
      },
      {
        id: 2478,
        logo_path: '/2v82HpzoKRveJEJcGHkeTcktMRM.png',
        name: 'Tochigi TV',
        origin_country: 'JP',
      },
    ],
    next_episode_to_air: {
      air_date: '2025-02-23',
      episode_number: 20,
      episode_type: 'standard',
      id: 5891815,
      name: 'Looking Up Was Tiring Me Out',
      overview: '',
      production_code: '',
      runtime: null,
      season_number: 1,
      show_id: 127532,
      still_path: null,
      vote_average: 0,
      vote_count: 0,
    },
    number_of_episodes: 25,
    number_of_seasons: 1,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '俺だけレベルアップな件',
    overview:
      'They say whatever doesn’t kill you makes you stronger, but that’s not the case for the world’s weakest hunter Sung Jinwoo. After being brutally slaughtered by monsters in a high-ranking dungeon, Jinwoo came back with the System, a program only he could see, that’s leveling him up in every way. Now, he’s inspired to discover the secrets behind his powers and the dungeon that spawned them.',
    popularity: 1508.312,
    poster_path: '/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg',
    production_companies: [
      {
        id: 13113,
        logo_path: '/xV5tPYKZhP2Ko9dOh5A3FahuKsx.png',
        name: 'A-1 Pictures',
        origin_country: 'JP',
      },
      {
        id: 2883,
        logo_path: '/rDYExnBV61jGQnkhVVrPN4Yl7O1.png',
        name: 'Aniplex',
        origin_country: 'JP',
      },
      { id: 163862, logo_path: null, name: 'Netmarble', origin_country: 'KR' },
      { id: 217720, logo_path: null, name: 'D&C Media', origin_country: 'KR' },
      {
        id: 210441,
        logo_path: '/kRGq6Eo3OgwnuLxijYYUIRpeCj9.png',
        name: 'Kakao piccoma',
        origin_country: 'JP',
      },
      {
        id: 198847,
        logo_path: '/ZylO1yrMIcy6VNFccPpHqo1qSZ.png',
        name: 'Crunchyroll',
        origin_country: 'US',
      },
      {
        id: 98553,
        logo_path: '/gNZh44MgDBwipGA9LwozlALjSdE.png',
        name: 'Crunchyroll',
        origin_country: 'JP',
      },
    ],
    production_countries: [
      { iso_3166_1: 'JP', name: 'Japan' },
      { iso_3166_1: 'KR', name: 'South Korea' },
      { iso_3166_1: 'US', name: 'United States of America' },
    ],
    seasons: [
      {
        air_date: '2024-02-25',
        episode_count: 1,
        id: 379694,
        name: 'Specials',
        overview: '',
        poster_path: '/hUQRnwRuVtz0CRZhUiOA26gXRoU.jpg',
        season_number: 0,
        vote_average: 0,
      },
      {
        air_date: '2024-01-07',
        episode_count: 25,
        id: 199167,
        name: 'Solo Leveling',
        overview:
          'It\'s been over a decade since the sudden appearance of the "gates"—the paths that connect our world with a different dimension. Since then, certain humans have awakened to supernatural powers. We call these individuals "hunters." Hunters make their living by using their powers to conquer dungeons inside the gates. In this world of tough customers, the low-ranked hunter Jinwoo Sung is known as "the weakest hunter of all mankind." One day, Jinwoo gets fatally injured when he runs into high-rank double dungeons hidden within a low-rank dungeon. Just then, a mysterious quest window appears in front of him.',
        poster_path: '/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg',
        season_number: 1,
        vote_average: 8.4,
      },
    ],
    spoken_languages: [
      { english_name: 'Japanese', iso_639_1: 'ja', name: '日本語' },
    ],
    status: 'Returning Series',
    tagline: 'He used to be the weakest.',
    type: 'Scripted',
    vote_average: 8.5,
    vote_count: 722,
  },

  {
    adult: false,
    backdrop_path: '/mQJVtl7SYjNLwjsUZZsITmAxtdU.jpg',
    created_by: [
      {
        credit_id: '5ab36c76c3a368615b004c6e',
        gender: 2,
        id: 347335,
        name: 'Josh Heald',
        original_name: 'Josh Heald',
        profile_path: '/gAGqe7l5VMTdVZuah2YczbXOJUl.jpg',
      },
      {
        credit_id: '5ab47d649251417b020149ed',
        gender: 2,
        id: 68844,
        name: 'Hayden Schlossberg',
        original_name: 'Hayden Schlossberg',
        profile_path: '/kLkKtht08e9Z451RpD5l5ebpwZu.jpg',
      },
      {
        credit_id: '64511fa5e942ee0e37e700e5',
        gender: 2,
        id: 68843,
        name: 'Jon Hurwitz',
        original_name: 'Jon Hurwitz',
        profile_path: '/fl3yAMOLbQFF86m8amwH2Ufntjs.jpg',
      },
    ],
    episode_run_time: [],
    first_air_date: '2018-05-02',
    genres: [
      { id: 10759, name: 'Action & Adventure' },
      { id: 18, name: 'Drama' },
      { id: 35, name: 'Comedy' },
    ],
    homepage: 'https://www.netflix.com/title/81002370',
    id: 77169,
    in_production: false,
    languages: ['en'],
    last_air_date: '2025-02-13',
    last_episode_to_air: {
      air_date: '2025-02-13',
      episode_number: 15,
      episode_type: 'finale',
      id: 5505565,
      name: 'Ex-Degenerate',
      overview:
        'Fierce rivalries. Fresh opportunities. Daniel and Johnny find themselves back where it all began — and the stakes have never been higher.',
      production_code: '',
      runtime: 49,
      season_number: 6,
      show_id: 77169,
      still_path: '/tfB0zgSSPV5jpa0PM2iycDjQ70p.jpg',
      vote_average: 9.8,
      vote_count: 4,
    },
    name: 'Cobra Kai',
    networks: [
      {
        id: 213,
        logo_path: '/wwemzKWzjKYJFfCeiB57q3r4Bcm.png',
        name: 'Netflix',
        origin_country: '',
      },
      {
        id: 1436,
        logo_path: '/291gKkFoCfbpKXJD2jMn3QeZlJ4.png',
        name: 'YouTube Premium',
        origin_country: 'US',
      },
    ],
    next_episode_to_air: null,
    number_of_episodes: 65,
    number_of_seasons: 6,
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Cobra Kai',
    overview:
      'This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.',
    popularity: 2389.765,
    poster_path: '/6GDW4EsgsXlYrL1ASb5eCHQK4er.jpg',
    production_companies: [
      {
        id: 101024,
        logo_path: null,
        name: 'Hurwitz & Schlossberg Productions',
        origin_country: 'US',
      },
      {
        id: 11073,
        logo_path: '/aCbASRcI1MI7DXjPbSW9Fcv9uGR.png',
        name: 'Sony Pictures Television',
        origin_country: 'US',
      },
      {
        id: 907,
        logo_path: '/ca5SWI5uvU985f8Kbb4xc8AmVWH.png',
        name: 'Overbrook Entertainment',
        origin_country: 'US',
      },
    ],
    production_countries: [
      { iso_3166_1: 'US', name: 'United States of America' },
    ],
    seasons: [
      {
        air_date: '2018-05-02',
        episode_count: 10,
        id: 99459,
        name: 'Season 1',
        overview:
          'Decades after the tournament that changed their lives, the rivalry between Johnny and Daniel reignites.',
        poster_path: '/lLrKXnM3WPEtrPCd1aTHT6x3hn.jpg',
        season_number: 1,
        vote_average: 8.2,
      },
      {
        air_date: '2019-04-24',
        episode_count: 10,
        id: 120052,
        name: 'Season 2',
        overview:
          'Johnny continues building a new life, but a face from his past could disrupt his future. Meanwhile, Daniel opens a Miyagi-Do studio to rival Cobra Kai.',
        poster_path: '/77kyNXN6yCRjDt9eBMj96vLMx8W.jpg',
        season_number: 2,
        vote_average: 8.1,
      },
      {
        air_date: '2021-01-01',
        episode_count: 10,
        id: 160283,
        name: 'Season 3',
        overview:
          'With a new sensei at the helm of the Cobra Kai dojo, a three-way feud takes center stage. Old grudges — like Cobra Kai — never die.',
        poster_path: '/f9ccj6MfeAsOk1qAqpifJwzxdfn.jpg',
        season_number: 3,
        vote_average: 8.2,
      },
      {
        air_date: '2021-12-31',
        episode_count: 10,
        id: 197131,
        name: 'Season 4',
        overview:
          'Faced with a common enemy, Daniel and Johnny decide to start working together while Kreese looks to the past for a new ally of his own.',
        poster_path: '/hETMqMZYTBtVrA4A8AcLw5w76Xa.jpg',
        season_number: 4,
        vote_average: 8.5,
      },
      {
        air_date: '2022-09-09',
        episode_count: 10,
        id: 292695,
        name: 'Season 5',
        overview:
          'As Terry leads Cobra Kai into a new regime, Daniel, Johnny and an old ally join forces in a battle that goes way beyond the mat.',
        poster_path: '/u2o6NDi5aNQ3SfyN1kZSXBaKoHK.jpg',
        season_number: 5,
        vote_average: 8.2,
      },
      {
        air_date: '2024-07-17',
        episode_count: 15,
        id: 325233,
        name: 'Season 6',
        overview:
          'With the global tournament approaching, Daniel and Johnny work to rebuild their team. But old enemies and new threats stand in the way of victory.',
        poster_path: '/dC88tPr0RwuKe0O16hh8AevlKcO.jpg',
        season_number: 6,
        vote_average: 8.7,
      },
    ],
    spoken_languages: [
      { english_name: 'English', iso_639_1: 'en', name: 'English' },
    ],
    status: 'Ended',
    tagline: 'Back in the Valley. One final fight.',
    type: 'Scripted',
    vote_average: 8.211,
    vote_count: 6451,
  },

  {
    adult: false,
    backdrop_path: '/odVlTMqPPiMksmxpN9cCbPCjUPP.jpg',
    created_by: [],
    episode_run_time: [24],
    first_air_date: '2024-01-07',
    genres: [
      { id: 10759, name: 'Action & Adventure' },
      { id: 10765, name: 'Sci-Fi & Fantasy' },
      { id: 16, name: 'Animation' },
    ],
    homepage: 'https://sololeveling-anime.net',
    id: 127532,
    in_production: true,
    languages: ['ja'],
    last_air_date: '2025-02-16',
    last_episode_to_air: {
      air_date: '2025-02-16',
      episode_number: 19,
      episode_type: 'standard',
      id: 5891814,
      name: 'The 10th S-Rank Hunter',
      overview:
        "Jinwoo officially becomes an S-Rank hunter, allowing him to finalize his preparations for the Demon's Castle.",
      production_code: '',
      runtime: 24,
      season_number: 1,
      show_id: 127532,
      still_path: '/zmRqLXqOMR2zVJ7bn9wwBsakOKh.jpg',
      vote_average: 9,
      vote_count: 2,
    },
    name: 'Solo Leveling',
    networks: [
      {
        id: 343,
        logo_path: '/9rNqtDYAnD6yTOutvHI3synSEs2.png',
        name: 'Gunma TV',
        origin_country: 'JP',
      },
      {
        id: 614,
        logo_path: '/hSdroyVthq3CynxTIIY7lnS8w1.png',
        name: 'Tokyo MX',
        origin_country: 'JP',
      },
      {
        id: 861,
        logo_path: '/JQ5bx6n7Qmdmyqz6sqjo5Fz2iR.png',
        name: 'BS11',
        origin_country: 'JP',
      },
      {
        id: 2478,
        logo_path: '/2v82HpzoKRveJEJcGHkeTcktMRM.png',
        name: 'Tochigi TV',
        origin_country: 'JP',
      },
    ],
    next_episode_to_air: {
      air_date: '2025-02-23',
      episode_number: 20,
      episode_type: 'standard',
      id: 5891815,
      name: 'Looking Up Was Tiring Me Out',
      overview: '',
      production_code: '',
      runtime: null,
      season_number: 1,
      show_id: 127532,
      still_path: null,
      vote_average: 0,
      vote_count: 0,
    },
    number_of_episodes: 25,
    number_of_seasons: 1,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '俺だけレベルアップな件',
    overview:
      'They say whatever doesn’t kill you makes you stronger, but that’s not the case for the world’s weakest hunter Sung Jinwoo. After being brutally slaughtered by monsters in a high-ranking dungeon, Jinwoo came back with the System, a program only he could see, that’s leveling him up in every way. Now, he’s inspired to discover the secrets behind his powers and the dungeon that spawned them.',
    popularity: 1508.312,
    poster_path: '/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg',
    production_companies: [
      {
        id: 13113,
        logo_path: '/xV5tPYKZhP2Ko9dOh5A3FahuKsx.png',
        name: 'A-1 Pictures',
        origin_country: 'JP',
      },
      {
        id: 2883,
        logo_path: '/rDYExnBV61jGQnkhVVrPN4Yl7O1.png',
        name: 'Aniplex',
        origin_country: 'JP',
      },
      { id: 163862, logo_path: null, name: 'Netmarble', origin_country: 'KR' },
      { id: 217720, logo_path: null, name: 'D&C Media', origin_country: 'KR' },
      {
        id: 210441,
        logo_path: '/kRGq6Eo3OgwnuLxijYYUIRpeCj9.png',
        name: 'Kakao piccoma',
        origin_country: 'JP',
      },
      {
        id: 198847,
        logo_path: '/ZylO1yrMIcy6VNFccPpHqo1qSZ.png',
        name: 'Crunchyroll',
        origin_country: 'US',
      },
      {
        id: 98553,
        logo_path: '/gNZh44MgDBwipGA9LwozlALjSdE.png',
        name: 'Crunchyroll',
        origin_country: 'JP',
      },
    ],
    production_countries: [
      { iso_3166_1: 'JP', name: 'Japan' },
      { iso_3166_1: 'KR', name: 'South Korea' },
      { iso_3166_1: 'US', name: 'United States of America' },
    ],
    seasons: [
      {
        air_date: '2024-02-25',
        episode_count: 1,
        id: 379694,
        name: 'Specials',
        overview: '',
        poster_path: '/hUQRnwRuVtz0CRZhUiOA26gXRoU.jpg',
        season_number: 0,
        vote_average: 0,
      },
      {
        air_date: '2024-01-07',
        episode_count: 25,
        id: 199167,
        name: 'Solo Leveling',
        overview:
          'It\'s been over a decade since the sudden appearance of the "gates"—the paths that connect our world with a different dimension. Since then, certain humans have awakened to supernatural powers. We call these individuals "hunters." Hunters make their living by using their powers to conquer dungeons inside the gates. In this world of tough customers, the low-ranked hunter Jinwoo Sung is known as "the weakest hunter of all mankind." One day, Jinwoo gets fatally injured when he runs into high-rank double dungeons hidden within a low-rank dungeon. Just then, a mysterious quest window appears in front of him.',
        poster_path: '/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg',
        season_number: 1,
        vote_average: 8.4,
      },
    ],
    spoken_languages: [
      { english_name: 'Japanese', iso_639_1: 'ja', name: '日本語' },
    ],
    status: 'Returning Series',
    tagline: 'He used to be the weakest.',
    type: 'Scripted',
    vote_average: 8.55,
    vote_count: 723,
  },
];
